# The Travis build will test both Linux AND OSX distributions, but language
# needs to be overridden to "generic" for Mac, otherwise the build will fail
# until Python is downloaded via Homebrew (which is handled in the
# before_install.sh). Note that none of the test envs or wheels test/create
# artifacts on <64 bit Linux or Mac. All artifacts are 64-bit ONLY.

language: python
sudo: required

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

before_install:
  - source build_tools/travis/before_install.sh
env:
  global:
    - PYMODULE=bear
    - TEST_DIR=/tmp/bear
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    # - TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"  # only for test!
    - TWINE_USERNAME="tgsmith61591.gh"
    - secure: CBeKNP+qy0Jtg8SqM6FDT4Qfn8RVO25sYEcg518wRczQcSpIO0E5bTjBoDGZdl6WguG8QCYLNTt3ll3NY1AntVSVG5m0X6dyHRN+hTOJw59KmQcE7UXvhvwpA98DEnXRPf2CCBXZnDDyYmhHH6c0VlCHhurvMfs6f9JhUOR7yJvz5pMg42uP0at2odkNa/G086+6+yVnkt/rfYYXLgxAOVOfbt7GyLiPp7CX3WenCCroH9gw6FQVsOw+swEZ7xYep4VgaO029b+nExFNjlA9MXB1i3oVVkRBTk8UfsOg82kjfi4SYSfI/qVVY7ivcxbjR/K7HkMi34Mcq/0KTtmRFaO3++hcvPEHuk0CmtN9zprDO/Muan2HBytG/p6ZbK9lEA1coOcREl/4wK5xAmGadZI5WHPK+HF3sTjni4dgDb10AbyctV1B/3I+yoxdY5Jt7eHD1Qu3zu6UnxsW+oLSlyQH3YgbBWGcwAa401bvvE92d4oRvYq0maV5oLk+QwPk8JyAX2ejrslx1o83Xs38qt4wPXTm+Ky4peHV3HbbFYQa1+lrVBHAew8ahUF+1P7oSudoZZkFuks3kouFUp/ENguFLTQNT/sq1SEhMmv5AZ4rcUatY0FiBL1Q3a9DMdqh2T/r2vow1UDPKcUWE8pqtHltMuzaJ82LaZhIdCsD7Ik=

matrix:
  include:
    # This environment tests the oldest supported anaconda env.
    - os: linux
      dist: trusty
      services:
        - docker
      env: DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE=true
           DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
           DOCKER_CONTAINER_NAME="bearcontainer" DEPLOY=true

    # This environment tests the same conditions as above, but tests against
    # MAC OS X
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE=true DEPLOY=true

    # This environment tests Python 3.5 support on linux
    - os: linux
      dist: trusty
      services:
        - docker
      env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE=true DEPLOY=true
           DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
           DOCKER_CONTAINER_NAME="bearcontainer"

    # This environment tests Python 3.5 support on MAC OS X
    - os: osx
      language: generic
      env: DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE=true DEPLOY=true

    # This environment tests the newest supported Anaconda release (4.x) and
    # runs on linux
    - os: linux
      dist: trusty
      env: DISTRIB="conda" PYTHON_VERSION="3.6.1"
           COVERAGE=true DEPLOY=false TEST_DOCSTRINGS="true"

install: source build_tools/travis/install.sh
before_script: bash build_tools/travis/before_script.sh
script: bash build_tools/travis/test_script.sh

# we set +e to re-instate the error-tolerant state. The problem is Travis is broken on Mac OS
# builds right now due to Issue 6307 (https://github.com/travis-ci/travis-ci/issues/6307)
# and fails at the end of a successful build. This will allow the build to recover even if
# a non-zero status code is encountered. (had `- set +e`)
after_success:
  - source build_tools/travis/after_success.sh  # || echo "shell_session_update failed"
  # Build the wheels every time so we can debug
  - bash build_tools/travis/build_wheels.sh
  - ls dist/

deploy:
  provider: script
  skip_cleanup: true
  script: python -m twine upload --skip-existing dist/*.whl
  on:
    tags: true # Upload on tagged releases
    condition: "$DEPLOY = true"
